services:
  db:
    image: postgres:18-alpine
    container_name: book_booker_db
    environment:
      POSTGRES_DB: book_booker
      POSTGRES_USER: book_user
      POSTGRES_PASSWORD: book_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U book_user -d book_booker"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
